#!/usr/bin/env ruby
feature = ARGV.first
feature_dir = File.dirname(feature)
# look up to two levels above the feature
ultimate_parent = (0 .. 2).
                  map{ |depth| feature_dir + ("/.." * depth) }.
                  select{ |dir| File.exist?(dir + "/support") }.
                  first
system "cucumber", "-r", ultimate_parent, feature
