#!/usr/bin/env ruby

templates = Dir["app/views/**/*.html.erb"]

def line_for(lines, text)
  (1 .. lines.length).to_a.zip(lines).each do |num, line|
    return num if line.match(text)
  end
  return 0
end

templates.each do |path|
  html = File.read(path).gsub(%r!<%.*?%>!m, "")
  chunks = html.split(%r{<script.*?</script>|<!--.*?-->|<[^>]+>|\n}m).map{ |s| s.strip }.select{ |s| s != "" }
  lines = html.split(/\n/)
  chunks.each do |chunk|
    puts "#{path}|#{line_for(lines, chunk)}| #{chunk}"
  end
end
