#!/usr/bin/env ruby

EXTENSIONS = %w[ rb erb html rhtml js sql ]

ARGV.each do |dir|
  Dir["#{dir}/**/*.{#{EXTENSIONS.join(',')}}"].each do |path|
    src = File.read(path)
    dest = src.split(/\n/).map{ |ln| ln.rstrip }.join("\n")
    next if src == dest
    File.open(path, 'w') do |f|
      f.puts(dest)
    end
    puts path
  end
end
