#!/usr/bin/env ruby

EXTENSIONS = %w[ c h rb haml erb html rhtml js sql yml feature md css scss ]

ARGV.each do |dir|
  Dir["#{dir}/**/*.{#{EXTENSIONS.join(',')}}"].each do |path|
    src = File.read(path)
    dest = src.gsub(/\t/, "  ").gsub(/ +$/, '').gsub(/\n\n+/, "\n\n")
    dest << "\n" unless dest =~ /\n\z/

    next if src == dest
    File.open(path, 'w') do |f|
      f << dest
    end
    puts path
  end
end
