#!/usr/bin/env ruby

params = {}
key = nil
while ARGV.first =~ /^-/
  params[ARGV.shift] = ARGV.shift
end

title = params.delete('-t') || params.delete('--song') || 'Part'
offset = (params.delete('--start') || 1).to_i
common = params.inject(''){ |s, (k,v)| s << ' ' << [k,v].compact.map{ |a| %{"#{a}"} }.join(' ') }

ARGV.sort.each_with_index do |file, i|
  track = i + offset
  system %{id3v2 #{common} --track "#{track}" --song "#{title} #{track}" "#{file}"}
end
