#!/usr/bin/env ruby

params = {}
key = nil
ARGV.each do |a|
  if a =~ /^-/
    key = a
    params[key] = nil
  else
    params[key] = a
  end
end
title = params.delete('-t') || params.delete('--song') || 'Part'
common = params.inject(''){ |s, (k,v)| s << ' ' << [k,v].compact.map{ |a| %{"#{a}"} }.join(' ') }

Dir['*.mp3'].sort.each_with_index do |file, i|
  system %{id3v2 #{common} --track "#{i+1}" --song "#{title} #{i+1}" "#{file}"}
end
