#!/usr/bin/env ruby

require 'open-uri'
require 'uri'
require 'htmlentities'

ARGV.each do |uri|
    begin
        open(uri) do |fp|
            html = fp.read
            html.scan(%r!<a.*?href=['"]?(http[^"'\s>]+)!im) do
                link = HTMLEntities.new.decode(URI.join(uri, $1).to_s)
                puts link
            end
        end
    rescue Exception => e
        $stderr.puts("Error: #{e.to_s}")
    end
end

