#!/usr/bin/env ruby
require "optparse"

DEFAULT_DICT = "/usr/share/dict/words"

options = {
  parts: 4,
  passwords: 20
}

instructions = <<END
  The default dictionary can be set via the DICT environment variable; the
  default is #{DEFAULT_DICT}.
END

ARGV.options{ |o|
  o.separator instructions
  o.on("-d", "--digits", "Use digits"
      ) { options[:digits] = true }
  o.on("-s", "--spaces", "Use spaces"
      ) { options[:spaces] = true }
  o.on("-y", "--symbols", "Use symbols"
      ) { options[:symbols] = true }
  o.on("-c", "--capitals", "Use capital letters"
      ) { options[:capitals] = true }
  o.on("-n", "--passwords=NUM", "Number of passwords to generate (default #{options[:passwords]})"
      ) { |v| options[:passwords] = v.to_i }
  o.on("-p", "--parts=NUM", "Number of parts to use (default #{options[:parts]})"
      ) { |v| options[:parts] = v.to_i }
  o.on("-h", "--help", "Show usage instructions"
      ) { puts o; exit }
}.parse!

DICT = ENV["DICT"] || DEFAULT_DICT

WORDS = File.read(DICT).scan(/\w+/).select{ |w| w.length >= 4 && w.length <= 8 }
CAPITALS = WORDS.map { |w| w.sub(/^./) { $&.upcase }}
SYMBOLS = %w[ ! @ # $ % ^ & * ( ) - _ = + ~ { } ; : , < . > / ? ]
DIGITS = %w[ 1 2 3 4 5 6 7 8 9 0 ]

parts = []
parts << DIGITS if options[:digits]
parts << SYMBOLS if options[:symbols]
parts << CAPITALS if options[:capitals]
parts << WORDS while parts.length < options[:parts]

def pick(array)
  array[rand(array.length)]
end

options[:passwords].times do
  puts parts.shuffle.map { |a| pick(a) }.join(options[:spaces] ? " " : "")
end
