#!/usr/bin/env ruby
WORDS = File.read("/usr/share/dict/words").scan(/\w+/).select{ |w| w.length >= 4 && w.length <= 8 }
SIGILS = %w[ ! @ # $ % ^ & * ( ) - _ = + ~ { } ; : , < . > / ? 1 2 3 4 5 6 7 8 9 0 ]
PATTERNS = [
  [WORDS,  SIGILS, SIGILS, WORDS ],
  [SIGILS, WORDS,  SIGILS, WORDS ],
  [WORDS,  SIGILS, WORDS,  SIGILS]
]

def pick(array)
  array[rand(array.length)]
end

(ARGV.first || 1).to_i.times do
  puts( pick(PATTERNS).map{ |s| pick(s) }.join )
end

