#!/usr/bin/env ruby

displays = Hash[`xrandr`.scan(/^([A-Z]+\d+) (dis)?connected/).map { |parts|
  [parts[0], parts[1] != "dis"]
}]

internal = displays.keys.select { |k| k =~ /^LVDS/ }
external = displays.keys - internal
connected = (external.select { |k| displays[k] } + internal)[0,1]
disconnected = displays.keys - connected

commands = [
  disconnected.map { |n| "--output #{n} --off" },
  connected.map { |n| "--output #{n} --auto" }
].compact.join(" ")

system "xrandr #{commands}"
system "xset dpms force on"
