#!/usr/bin/env ruby
require 'rexml/document'
require 'open-uri'

friendid = ARGV[0]
ss_xml_url = "http://mediaservices.myspace.com/services/media/photosXML.ashx?friendid=#{friendid}"
x = open(ss_xml_url){ |io| io.read }
doc = REXML::Document.new(x)
buffer, url = nil

REXML::XPath.each(doc, "//file") do |node|
  url = node.text
  buffer = open(url){ |io| io.read }
  File.open(File.basename(url), 'wb') do |io|
    io << buffer
  end
end
