#!/usr/bin/env ruby
require 'mechanize'
require 'csv'

email, password = nil
config_file = File.join(ENV['HOME'], '.newnet')
eval(File.read(config_file), binding, config_file, 1)

agent = WWW::Mechanize.new

# Sign in
page = agent.get('https://orderform.co.uk/login/index.php?form=orac')
form = page.form('login')
form.emailaddress = email
form.password     = password
page = agent.submit(form, form.buttons.first)

# Go to bandwidth page
page = agent.get(page.search("//a").map{ |a| a['href'] }.find{ |h| h =~ /ADSLAccountDetails/ })
font_elements = page.search("//font").map{ |a| a.inner_html }
i = font_elements.index('Included Monthly Bandwidth Allowance')
allowance = font_elements[i+1].to_i

# Get bandwidth CSV for current month
form = page.form('getbwu')
form.monthFilter = Time.now.strftime('%Y-%m')
csv = agent.submit(form, form.buttons.first).body

headers = nil
data = {}
CSV::Reader.parse(csv) do |row|
  if headers
    headers.zip(row).each do |k, v|
      data[k] = v
    end
  else
    headers = row.to_a
  end
end
prediction = data['Current Month Prediction'].to_f
usage = data['Bandwidth Used'].to_f
puts "Used:      %2.2f GB" % usage
puts "Predicted: %2.2f GB" % prediction
puts "Allowance: %2.2f GB" % allowance
