#!/usr/bin/env ruby
require "date"
require "json"
require "mechanize"

START_URL = "https://www.plus.net/view_my_broadband_usage/index.php"

UNIT_MULTIPLIERS = {
  "TB" => 2**40,
  "GB" => 2**30,
  "MB" => 2**20,
  "KB" => 2**10
}

def extract_bytes(s)
  match = s.match(/(\d+(?:\.\d+)?)(#{UNIT_MULTIPLIERS.keys.join("|")})/)
  raise "Couldn't find number in '#{s}'" unless match
  match[1].to_f * UNIT_MULTIPLIERS.fetch(match[2])
end

def format_bytes(n)
  gb_value = n / UNIT_MULTIPLIERS["GB"]
  "%.2f" % gb_value
end

config = JSON.parse(File.read(File.join(ENV["HOME"], ".config", "plusnet.json")))

agent = Mechanize.new

# Sign in
page = agent.get(START_URL)
form = page.forms.find { |f| f.action == START_URL }
form.username = config.fetch("username")
form.password = config.fetch("password")
page = agent.submit(form, form.buttons.first)

peak, off_peak, allowance = [
  ".vmbuMonthTotal .usageAllowance",
  ".vmbuGraphLegendRight .content",
  ".vmbuMonthTotal .bottomLine",
].map { |query| extract_bytes(page.at(query).text) }

date_from, date_to, = page.at(".vmbuProductDetails").text.
  scan(/\b[A-Z][a-z]{2} \d{1,2} 20\d{2}/).
  map { |s| Date.parse(s) }

daily_allowance = allowance / (date_to - date_from + 1)
budgeted_usage = daily_allowance * (Date.today - date_from + 1)

fields = {
  "Peak" => peak,
  "Budget" => budgeted_usage,
  "Off-peak" => off_peak,
  "Allowance" => allowance
}

fields.each do |name, value|
  puts "#{name}: #{format_bytes(value)}"
end
