#!/usr/bin/env ruby

LINE_LENGTH = 78
Dir.chdir(ARGV.first) if ARGV.first

Dir['**/*'].each do |path|
  next unless File.file?(path)
  next if File.basename(path) =~ /^\./
  separator = '*' * path.length
  puts(separator, path, separator, '')
  File.read(path).split(/\r\n|\n|\r/).each_with_index do |line, i|
    puts "%3d  %s" % [i+1, line]
  end
  puts
end

