#!/bin/bash

resolution=300
width=210
height=297
quality=75
output_dir="$HOME/Pictures/Scans"
filename=""
mode=Color

usage() {
cat << EOF
usage: $0 options

OPTIONS:
    -f      Filename (default: current date and time)
    -c      Colour (default)
    -g      Greyscale
    -m      Mono
    -r      Resolution in DPI (default: $resolution)
    -q      Image quality (default: $quality)
    -x      Width in mm (default: $width)
    -y      Height in mm (default: $height)
    -p      Preset page size: a4p a5p a5l
    -h      Show this message
EOF
}

while getopts “r:q:x:y:p:f:hcgm” OPTION; do
  case $OPTION in
    h)
      usage
      exit
      ;;
    r)
      resolution=$OPTARG
      ;;
    q)
      quality=$OPTARG
      ;;
    p)
      case $OPTARG in
        a4p)
          width=210
          height=297
          ;;
        a5l)
          width=210
          height=148
          ;;
        a5p)
          width=148
          height=210
          ;;
      esac
      ;;
    x)
      width=$OPTARG
      ;;
    y)
      height=$OPTARG
      ;;
    f)
      filename=$OPTARG
      ;;
    c)
      mode=Color
      ;;
    g)
      mode=Gray
      ;;
    m)
      mode=Lineart
      ;;
    ?)
      usage
      exit
      ;;
  esac
done

if [ "$filename" = "" ]; then
  output_file="$output_dir/$(date -u +'%FT%T%z.jpg')"
else
  output_file="$output_dir/$filename"
fi

echo "Scanning to $output_file ..."

mkdir -p $output_dir
scanimage --resolution $resolution --mode $mode -x $width -y $height |\
  convert - -density $resolution -quality $quality "$output_file"
