#!/usr/bin/env ruby
require "stringio"
$stderr = StringIO.new # Silence Nokogiri's whining
require "mechanize"
$stderr = STDERR

STATUS_COLORS = {
  "Good service"  => "green",
  "Minor delays"  => "yellow",
  "Severe delays" => "red",
}
STATUS_COLORS.default = "red"

class Line
  attr_reader :name, :short_name, :color
  def initialize(color, name, short_name=nil)
    @color      = color
    @name       = name
    @short_name = short_name || name
  end

  attr_writer :status
  def status_color
    STATUS_COLORS[status]
  end

  def status
    @status.gsub(/[^a-z ]+/i, "")
  end

  def ok?
    status == "Good service"
  end
end

lines = {
  "bakerloo"           => Line.new("#AE6118", "Bakerloo"),
  "central"            => Line.new("#E41F1F", "Central"),
  "circle"             => Line.new("#F8D42D", "Circle"),
  "district"           => Line.new("#00A575", "District"),
  "hammersmithandcity" => Line.new("#E899A8", "Hammersmith & City", "H & C"),
  "jubilee"            => Line.new("#8F989E", "Jubilee"),
  "metropolitan"       => Line.new("#893267", "Met.", "Metropolitan"),
  "northern"           => Line.new("#000000", "Northern"),
  "piccadilly"         => Line.new("#0450A1", "Piccadilly"),
  "victoria"           => Line.new("#009FE0", "Victoria"),
  "waterlooandcity"    => Line.new("#70C3CE", "Waterloo & City", "W & C"),
}

agent = WWW::Mechanize.new
page   = agent.get('http://www.tfl.gov.uk/tfl/livetravelnews/realtime/tube/default.html')
page.search("#lines li").each do |li|
  line_key = li.search("h3").first["class"].split(/ /).first
  status = li.search("div").first.text
  line = lines[line_key]
  next unless line
  line.status = status
end

lines_with_problems = lines.values.reject{ |l| l.ok? }
name_width = lines_with_problems.map{ |l| l.short_name.length }.max
lines_with_problems.sort_by{ |l| l.name.upcase }.each do |line|
  puts "${color grey}#{line.short_name.ljust(name_width)} ${color #{line.status_color}}#{line.status}$color"
end
