#!/usr/bin/env ruby
require "open-uri"
require "fileutils"
include FileUtils

BUILD_ROOT = 'http://build.chromium.org/buildbot/snapshots'

def sh(*args)
  ok = system *args
  raise "Error running #{ args.inspect }" unless ok
end

os =
  case `uname -s`
  when /linux/i
    :linux
  when /darwin/i
    :mac
  else
    raise "Unknown OS"
  end

arch =
  case `uname -m`
  when /x86_64/
    :x86_64
  when /i\d86/
    :x86
  end

path_fragment =
  case os
  when :linux
    case arch
    when :x86_64
      "linux-64"
    when :x86
      "linux"
    else
      raise "Unknown architecture"
    end
  when :mac
    "mac"
  else
    raise "Unknown platform"
  end

archive = "chrome-#{ os }.zip"

platform_root = "#{ BUILD_ROOT }/chromium-rel-#{ path_fragment }"
version =
  ARGV.first ||
  open("#{ platform_root }/LATEST"){ |f| f.read }.
  scan(/\d+/)

Dir.chdir("/tmp")
sh %{curl -O "#{ platform_root }/#{ version }/#{ archive }"}
sh %{unzip "#{ archive }"}

target, directory =
  case os
  when :linux
    ["/opt/chrome-linux", "chrome-linux"]
  when :mac
    ["/Applications/Chromium.app", "chrome-mac/Chromium.app"]
  end

sh %{chmod -R a+rX "#{ directory }"}
old_target = target + ".old"
mv target, old_target
mv directory, target
rm_rf old_target
